version: 0.2

env:
  variables:
    LOG_LEVEL: 'error'

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm ci
      - npm run build
  build:
    commands:
      # - npm run cypress:ci
      - test $CYPRESS_APP_ENV = "live" && npm run test:linkey || true
reports:
  JunitReportsTest:
    files:
      - '**/*'
    base-directory: 'cypress/results' # Location of the reports
