name: Simorgh Lighthouse Tests

on:
  push:
    branches:
      - '**'
      - '!latest'
  pull_request:
    branches:
      - '**'
      - '!latest'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm ci

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            http://localhost:7080/news/articles/cn7k01xp8kxo
            http://localhost:7080/igbo
          runs: 5
          configPath: './lighthouse/lighthouserc.json'
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage


